apiVersion: apps/v1
kind: Deployment
metadata:
  name: legacy-app
  namespace: legacy-app-ns
  labels:
    app: legacy-app
spec:
  replicas: 3

  selector:
    matchLabels:
      app: legacy-app

  template:
    metadata:
      labels:
        app: legacy-app

      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"

    spec:
      containers:
      - name: legacy-app

        image: tosinseni255/ecommerce-app:latest

        imagePullPolicy: Always

        ports:
        - containerPort: 3000

        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"

        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 10
